### DISCUSSION TITLE
any way to whitelist channel so i dont see dislike number for specific channel?

### DISCUSSION THREAD

**Discussion by TecnikOfficial** [Anarios/return-youtube-dislike#1049] [Q&A]
i ws wondering is there a way in js script to make dislike turn off for some youtube channel ?

**Comment by krystian3w** [comment]
I think possible use CSS4:

```css
/* pseudocode - need correct selectors and attributes */
body description:has(a[aria-label=youtuber]) downvote-counter {
 display: none !important;
 visibility: hidden !important
}
/* pseudocode - need correct selectors and attributes */
```

For Firefox 121+ (124+ at mobile), Chromium 105+ and Safari 15.4+. *Support legacy browsers and Firefox 115 ESR should be need vanilla JS instead (less chance to glitch with still visible counter)*.

Harder will be in alternative app like newpipe fork.
