### ISSUE TITLE
(Bug): Duplicating likes on second click...

### ISSUE THREAD

**Issue by Leiloukou** [Anarios/return-youtube-dislike#645]
### Browser

Chrome

### Browser Version

Chrome 102, Windows 11.

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.2

### Video link where you see the problem

Any video under 1K likes, for example: https://www.youtube.com/watch?v=KJGD4RdwKWU

### What happened?

Sometimes when I watch a video, then click on the like button, this happens:

https://user-images.githubusercontent.com/95201376/173156123-2a6fa002-347d-4ef1-b820-8569fe316a9c.mp4

I forked the repo and traced **EVERYTHING**, but I can't seem to find where the problem is exactly.

### How to reproduce/recreate?

Go to a video with less than 1,000 likes, [Like this one](https://www.youtube.com/watch?v=KJGD4RdwKWU),
and click the like button two or three times. It will duplicate the like number, almost as if you used
the += operator, (in the source code at the reassigning of "likeButton.textContent"), but there is no
indication of that.

The only thing that I think might be the problem is you are trying to add an integer to a string.

**Comment by Leiloukou** [comment]
I would like to start contributing to open source, so could one of the admins please assign this to me?

**Comment by Leiloukou** [comment]
I am trying to get started contributing to open source,
so could one of the administrators assign this to me? 🧑‍💻

**Comment by Leiloukou** [comment]
Thank you.

**Comment by Leiloukou** [comment]
What is the difference between [ryd.content-script.js](https://github.com/Anarios/return-youtube-dislike/blob/main/Extensions/combined/ryd.content-script.js), and [ryd.background.js](https://github.com/Anarios/return-youtube-dislike/blob/main/Extensions/combined/ryd.background.js)? And if they are both used to change the like, should I modify both?

And what should I name the branch I will work on?

**Comment by Leiloukou** [comment]
Thank you, I will look into "mutation observers", and on the topic
of developing chrome extensions, I have made a few.

P.S. Do you have anyone working on this currently?

**Comment by Leiloukou** [comment]
I am trying to test my changes with "Load Unpacked",

**Comment by Leiloukou** [comment]
How do I test? It seems that the extension uses an API with
permissions I do not have.

**Comment by Leiloukou** [comment]
Sorry, now I'm back. And no I didn't build with npm. I will look at the package.json.

**Comment by Leiloukou** [comment]
I did `npm i`, then `npm run dev`,
after that pressed load unpacked in the
chrome extensions manager and got this:

```
Manifest file is missing or unreadable
Could not load manifest.
```

I started out by renaming the "manifest-chrome.json" file to
just "manifest.json", but that didn't work, and renaming it
back to "manifest-chrome.json" didn't work either.

Also I am testing the project from
`C:\myDevFolder\return-youtube-dislike\extensions\combined\`.
Should I load it as Userscript? I have no idea what Userscript is,
but I think I should not do it that way.

**Comment by Leiloukou** [comment]
Thank you. I forgot about the `contribute.md` file.

**Comment by Leiloukou** [comment]
The [CONTIBUTING.md](https://github.com/Anarios/return-youtube-dislike/blob/main/CONTRIBUTING.md#:~:text=in%20manifest.json-,npm%20start,-//%20to%20create%20the) says to use the `npm start` command,
and has no mention of `npm run dev`.

**Comment by Leiloukou** [comment]
It worked, but not as I hoped. The stylesheet does not work,
and the bug is gone without me writing a single line of code.

**Comment by Leiloukou** [comment]
![return-youbube-dislike-no-stylesheet](https://user-images.githubusercontent.com/95201376/173421205-04006afa-971e-4f2a-b5da-733394d19b6c.png)

Everything is monochrome, but when I use the real extension,
it is red and green.

**Comment by Leiloukou** [comment]
I looked in "content-style.css" in the /dist/chrome/ folder and
I noticed this:
```css
:root {
  /* --yt-spec-icon-disabled: #f44 !important;
  --yt-spec-text-primary: #4f4 !important; */
  /* --yt-spec-general-background-a: #000 !important;
  --yt-spec-general-background-b: #000 !important;
  --yt-spec-general-background-c: #000 !important;
  --yt-spec-brand-background-solid: #000 !important;
  --yt-spec-brand-background-primary: #000 !important;
  --yt-spec-brand-background-secondary: #000 !important; */
}

/* html:not(.style-scope)[dark], :not(.style-scope)[dark] {
  --yt-spec-general-background-a: #000 !important;
  --yt-spec-general-background-b: #000 !important;
  --yt-spec-general-background-c: #000 !important;
  --yt-spec-brand-background-solid: #000 !important;
  --yt-spec-brand-background-primary: #000 !important;
  --yt-spec-brand-background-secondary: #000 !important;
} */
```

> **Note:** I have not edited this file at all, so this is either from when I forked or from the `npm run dev` command.
