### ISSUE TITLE
Return YouTube Dislike doesn't work with user style

### ISSUE THREAD

**Issue by xeophyte** [Anarios/return-youtube-dislike#920]
### Have you tried to find similar open issues?

- [X] Yes, this issue is not a duplicate

### Browser

Vivaldi

### Browser Version

6.1.3009.3

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.9

### Video link where you see the problem

every yt video

### What happened?

Return YouTube Dislike doesn't work when this style is turned on:
https://userstyles.org/styles/123887/youtube-better-full-dark-theme-2022-arc
https://uso.kkx.one/style/123887
This is one of the best styles for YT and there is a conflict between extension and style. Dislike numbers and ratio bar are not visible.
https://i.imgur.com/z6wwCuD.png
https://i.imgur.com/MpzgN1F.png

### How to reproduce/recreate?

install Return YouTube Dislike as extension and the Youtube better full dark theme 2022 arc style

### Will you be available for follow-up questions to help developers diagnose & fix the issue?

Yes

**Comment by openforu** [comment]
Its not working because of old description style

CSS causing problem:

```
ytd-watch-metadata {
    display: none !important;
}
ytd-watch-flexy #info-contents,
ytd-watch-flexy #meta-contents {
    display: block !important;
}
```

**Comment by RikisuT** [comment]
> Its not working because of old description style
> 
> CSS causing problem:
> 
> ```
> ytd-watch-metadata {
>     display: none !important;
> }
> ytd-watch-flexy #info-contents,
> ytd-watch-flexy #meta-contents {
>     display: block !important;
> }
> ```
I have that snippet in my css script too.
You can modify the js version of the as I have done.
[DiffChecker](https://www.diffchecker.com/YAqplrrK/)
You can compare my edits with the original.
Also add these CSS lines to correct the positioning
```css
#menu-container {
  display: flex;
  flex-direction: column;
}
ytd-video-primary-info-renderer[flex-menu-enabled] #menu-container.ytd-video-primary-info-renderer {
    flex: inherit;
}
ytd-segmented-like-dislike-button-renderer
{
    margin-left: 2px!important;
    margin-bottom: 11px;
}
```
